# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rvikrama <rvikrama@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/09/26 13:25:32 by rvikrama          #+#    #+#              #
#    Updated: 2025/09/26 13:25:50 by rvikrama         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ex00

CC = c++

CFLAG = -Wall -Werror -Wextra -std=c++98 -g -O0 -fsanitize=address
# -g3 -O3 -O0 -fsanitize=address -fsanitize-recover=leak
# valgrind --leak-check=full --show-leak-kinds=all
# -g = gives error messages for debugging, needed by gdb / valgrind / helgrind

INC_DIR = includes
INC = -I$(INC_DIR)
SRC_DIR = src

SRC =	$(addprefix $(SRC_DIR)/, \
		main.cpp \
		Animal.cpp \
		Dog.cpp \
		Cat.cpp \
		WrongAnimal.cpp \
		WrongCat.cpp )

OBJ_FOLDER = obj_files


OBJ_SRC = $(patsubst %.cpp, $(OBJ_FOLDER)/%.o, $(SRC))

# color
GREEN = \033[0;32m
CYAN = \033[0;36m
RESET = \033[0m  	#white

all: $(NAME)

$(NAME) : $(OBJ_SRC)
	$(CC) $(CFLAG) $(OBJ_SRC) -o $(NAME)
		@echo "${CYAN}=========================================== \n${RESET}"
		@echo "${CYAN}██████╗  █████╗      ██╗ █████╗   ██╗   ██╗${RESET}"
		@echo "${CYAN}██╔══██╗██╔══██╗     ██║██╔══██╗  ██║   ██║${RESET}"
		@echo "${CYAN}██████╔╝███████║     ██║███████║  ██║   ██║${RESET}"
		@echo "${CYAN}██╔══██╗██╔══██║██   ██║██╔══██║  ╚██╗ ██╔╝${RESET}"
		@echo "${CYAN}██║  ██║██║  ██║╚█████╔╝██║  ██║██╗╚████╔╝ ${RESET}"
		@echo "${CYAN}╚═╝  ╚═╝╚═╝  ╚═╝ ╚════╝ ╚═╝  ╚═╝╚═╝ ╚═══╝  ${RESET}"
		@echo "${CYAN}=========================================== \n${RESET}"
		@echo "${GREEN}----------COMPILED DONE----------${RESET}"


$(OBJ_FOLDER)/%.o : %.cpp
	@mkdir -p $(dir $@)
	$(CC) $(CFLAG) $(INC) -c $< -o $@

clean:
	rm -rf $(OBJ_FOLDER)
	@echo "${GREEN}----------CLEANED----------\n${RESET}"

fclean : clean
	rm -f $(NAME)
	@echo "${GREEN}----------FULLY REMOVE----------\n${RESET}"

re : fclean all

.PHONY : all clean fclean re